{
 "title": "NodeProcess",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(describe_node_process_cpu_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "进程CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "describe_node_process_cpu_info{instance=\"${instance}\"}",
     "legendFormat": "{{name}} - Pid: {{pid}}"
    }
   ]
  },
  {
   "title": "进程内存",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "describe_node_process_memory_info{instance=\"${instance}\"}",
     "legendFormat": "{{name}} - Pid: {{pid}}"
    }
   ]
  },
  {
   "title": "进程文件打开数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "describe_node_process_openfiles_info{instance=\"${instance}\"}",
     "legendFormat": "{{name}} - Pid: {{pid}}"
    }
   ]
  }
 ]
}